import re
import time
from playwright.sync_api import Playwright, sync_playwright, expect, TimeoutError

def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=True, slow_mo=500)
    context = browser.new_context()
    page = context.new_page()

    page.goto("https://geo.whr.ai/login?utm_source=10times&utm_medium=web&utm_campaign=right_rail&hash=4IQjAPckGZDk9ArLj1D3pDYc8tvqFPX7ZsemflFWON0=&uid=1048476")
    time.sleep(5)
    page.goto("https://geo.whr.ai/internal/search/events")
    page.get_by_role("button", name="Skip").click()
    page.mouse.move(0, 500)
    page.get_by_role("link", name="Tracker").click()
    time.sleep(3)
    page.get_by_role("button", name="Create").click()
    page.get_by_role("button", name="Skip").click()
    time.sleep(3)
    page.get_by_role("link", name="Location and").click()
    page.get_by_role("button", name="Skip").click()
    page.get_by_role("tab", name="Center Point & Radius").click()
    page.get_by_role("combobox", name="E.g. Novotel, Hyderabad").click()
    page.get_by_role("combobox", name="E.g. Novotel, Hyderabad").fill("india")
    page.get_by_text("IndianOil").click()
    page.get_by_role("button", name="12 months").click()
    page.get_by_role("switch", name="Enable/Disable all advanced").click()
    page.get_by_role("textbox", name="Enter Tracker Name").click()
    page.get_by_role("textbox", name="Enter Tracker Name").fill("test")
    page.get_by_role("button", name="Save").click()
    page.get_by_role("button", name="Skip").click()
    page.get_by_role("button", name="Business Events").click()
    page.get_by_text("Table").click()
    time.sleep(5)
    page.get_by_text("Est. Visitors").click()
    page.get_by_text("Est. Exhibitors").click()
    page.get_by_text("Rank").click()
    page.get_by_text("Trust").click()
    page.get_by_text("Frequency").click()
    page.get_by_text("Forecasted").click()
    page.get_by_text("Inbound").click()
    page.get_by_text("International").click()
    page.get_by_text("Est. Impact ($)").click()
    page.get_by_role("link", name="Configurations").click()
    time.sleep(3)
    page.get_by_role("button", name="Maturity").click()
    page.get_by_role("radio", name="New").click()
    page.get_by_role("button", name="Save").click()
    page.get_by_role("button", name="Business Events").click()
    time.sleep(3)
    page.get_by_text("Table").click()
    page.get_by_text("Maturity").click()


    # ---------------------
    context.close()
    browser.close()

with sync_playwright() as playwright:
    run(playwright)