import re
import time
from playwright.sync_api import Playwright, sync_playwright, expect, TimeoutError

def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=True, slow_mo=500)
    context = browser.new_context()
    page = context.new_page()

    page.goto("https://gtm.whr.ai/login?utm_source=10times&utm_medium=web&utm_campaign=right_rail&hash=4IQjAPckGZDk9ArLj1D3pDYc8tvqFPX7ZsemflFWON0=&uid=1048476")
    time.sleep(5)
    page.goto("https://gtm.whr.ai/internal/search/events")
    page.get_by_role("button", name="Skip").click()
    page.mouse.move(0, 500)
    page.get_by_role("link", name="Tracker").click()
    time.sleep(3)
    page.get_by_role("button", name="Create").click()
    page.get_by_role("button", name="Skip").click()
    time.sleep(3)
    page.get_by_role("link", name="Competitor Track your competitor").click()
    page.get_by_role("button", name="Skip").click()
    page.get_by_role("textbox", name="Competitor Name or Website").click()
    page.get_by_role("textbox", name="Competitor Name or Website").fill("10times")
    page.get_by_text("+", exact=True).click()
    page.get_by_role("textbox", name="Competitor Name or Website").click()
    page.get_by_role("textbox", name="Competitor Name or Website").fill("cvent")
    page.get_by_text("+", exact=True).click()
    page.get_by_role("textbox", name="Competitor Name or Website").click()
    page.get_by_role("textbox", name="Competitor Name or Website").fill("allevents.in")
    page.get_by_text("+", exact=True).click()
    page.get_by_role("switch", name="Show ratings").click()
    page.get_by_role("switch", name="Enable/Disable all advanced").click()
    page.get_by_role("button", name="Estimated Visitors").click()
    page.get_by_role("checkbox", name="Nano").click()
    page.get_by_role("checkbox", name="Small").click()
    page.get_by_role("checkbox", name="Large").click()
    page.get_by_role("checkbox", name="Ultra").click()
    page.get_by_role("textbox", name="Enter Tracker Name").click()
    page.get_by_role("textbox", name="Enter Tracker Name").fill("test")
    page.get_by_role("button", name="Save").click()
    time.sleep(5)
    page.get_by_role("button", name="Skip").click()
    page.get_by_text("Table").click()
    page.get_by_text("Est. Visitors").click()
    page.get_by_text("Est. Exhibitors").click()
    page.get_by_text("Rank", exact=True).click()
    page.get_by_text("Event Rating").click()
    page.get_by_text("Trust").click()
    page.get_by_text("Frequency").click()
    page.get_by_text("Forecasted").click()
    page.get_by_text("Audience Zone").click()
    page.get_by_role("link", name="Configurations").click()
    time.sleep(5)
    page.get_by_role("button", name="Maturity").click()
    page.get_by_role("radio", name="Flagship").click()
    page.get_by_role("button", name="Save").click()
    time.sleep(5)
    page.get_by_text("Table").click()
    page.get_by_text("Maturity").click()

    # ---------------------
    context.close()
    browser.close()

with sync_playwright() as playwright:
    run(playwright)