import re
import time
from playwright.sync_api import Playwright, sync_playwright, expect, TimeoutError

def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=True, slow_mo=500)
    context = browser.new_context()
    page = context.new_page()

    page.goto("https://gtm.whr.ai/login?utm_source=10times&utm_medium=web&utm_campaign=right_rail&hash=4IQjAPckGZDk9ArLj1D3pDYc8tvqFPX7ZsemflFWON0=&uid=1048476")
    time.sleep(5)
    page.goto("https://gtm.whr.ai/internal/search/events")
    page.get_by_role("button", name="Skip").click()
    page.mouse.move(0, 500)
    page.get_by_role("link", name="Tracker").click()
    time.sleep(3)
    page.get_by_role("button", name="Create").click()
    page.get_by_role("button", name="Skip").click()
    page.get_by_role("link", name="Product and Topics").click()
    page.get_by_role("button", name="Skip").click()
    page.get_by_role("textbox", name="Type Products/Topics to").click()
    page.get_by_role("textbox", name="Type Products/Topics to").fill("ai")
    page.get_by_role("button", name="+").click()
    page.get_by_role("textbox", name="Type Products/Topics to").click()
    page.get_by_role("textbox", name="Type Products/Topics to").fill("machine")
    page.get_by_role("button", name="+").click()
    page.get_by_role("textbox", name="Type Products/Topics to").click()
    page.get_by_role("textbox", name="Type Products/Topics to").fill("event")
    page.get_by_role("button", name="+").click()
    page.get_by_role("textbox", name="Type Products/Topics to").click()
    page.get_by_role("textbox", name="Type Products/Topics to").fill("engine")
    page.get_by_role("button", name="+").click()
    page.get_by_role("switch", name="Show ratings").click()
    page.get_by_role("button", name="Estimated Visitors").click()
    page.get_by_role("checkbox", name="Nano").click()
    page.get_by_role("checkbox", name="Small").click()
    page.get_by_role("checkbox", name="Large").click()
    page.get_by_role("checkbox", name="Ultra").click()
    page.get_by_role("switch", name="Show Global & Touring in").click()
    page.get_by_role("button", name="Forecasted Status").locator("#forecasted-status").click()
    page.get_by_role("switch", name="Show Frequency in filter").click()
    page.get_by_role("switch", name="Show Estimated Exhibitors in").click()
    page.get_by_role("button", name="Event Ranking").click()
    page.get_by_role("switch", name="Rank").click()
    page.locator("#forecasted-status").nth(1).click()
    page.get_by_role("textbox", name="Enter Tracker Name").click()
    page.get_by_role("textbox", name="Enter Tracker Name").fill("test")
    page.get_by_role("button", name="Save").click()
    time.sleep(5)
    page.get_by_role("button", name="Skip").click()
    page.get_by_role("button", name="Upcoming Events").click()
    page.get_by_text("Table").click()
    time.sleep(3)
    page.locator("td button:has(svg.lucide-bookmark)").nth(3).click()
    page.get_by_role("radio", name="Bookmark").click()
    page.get_by_role("button", name="Submit").click()
    time.sleep(3)
    page.get_by_role("button", name="Bookmarked Events").click()
    page.get_by_role("button", name="Share").click()
    page.get_by_role("textbox", name="Invite others by email").click()
    page.get_by_role("textbox", name="Invite others by email").fill("ghanshyam@10times.com")
    page.get_by_role("button", name="Send Invite").click()
    page.get_by_text("Success", exact=True).click()
    page.get_by_role("region", name="Notifications (F8)").get_by_role("button").click()
    time.sleep(3)
    page.get_by_text("Map").click()
    time.sleep(2)
    page.get_by_role("button", name="Event List").click()
    page.get_by_text("Calendar").click()
    page.get_by_text("Table").click()
    page.get_by_role("button", name="Upcoming Events").click()
    time.sleep(3)
    time.sleep(3)
    page.get_by_role("button", name="Bookmarked Events").click()
    page.get_by_role("cell").filter(has_text=re.compile(r"^$")).get_by_role("button").click()
    page.get_by_role("radio", name="Un-Bookmark").click()
    page.get_by_role("button", name="Submit").click()

    # ---------------------
    context.close()
    browser.close()

with sync_playwright() as playwright:
    run(playwright)
